---
title: "Data Load and Clean"
output: html_notebook
---
  
```{r}
library(tidyverse)
```

```{r}
otu_table <- read_tsv("~/RMB/SoilDomestication/Data/total_dom_otu_table.tsv.gz")
tax <- readRDS("~/RMB/Reference/gg_otus_tax.rds")
```

```{r}
maize_map <- read_tsv("~/Google Drive/RMB/Analyses/Combo/maize_map.txt") %>%
  dplyr::select(host_common_name, host_subject_id, sample_type, collection_timestamp, SampleID, latitude, longitude) %>% 
  mutate(study = "maize_ley", sample_type = ifelse(host_subject_id == "Bulk Soil", "Bulk Soil", "Rhizosphere"))

grape_map <- read_tsv("~/Google Drive/RMB/Analyses/Combo/grapevine_map.txt") %>% 
  dplyr::select(host_subject_id, sample_type, collection_timestamp, SampleID, latitude, longitude) %>%
  mutate(host_common_name = "grape", study = "grape_gilbert")

cannabis_map <- read_tsv("~/Google Drive/RMB/Analyses/Combo/cannabis1_map.txt") %>% 
  dplyr::select(host_subject_id, sample_type, collection_timestamp, SampleID, latitude, longitude) %>% 
  mutate(host_common_name = "Cannabis", study = "cannabis")

rice_map <- read_tsv("~/Google Drive/RMB/Manuscript/PNAS/Edwards_PNAS/Data/FieldExperiment/field_map.txt") %>% 
  mutate(host_common_name = "Rice", sample_type = Compartment) %>% 
  mutate(SampleID = Description) %>% 
  dplyr::select(host_common_name, sample_type, SampleID) %>% 
  mutate(study = "rice_edwards")

rice_knight <- read_tsv("~/Google Drive/RMB/Analyses/Combo/rice_knight_map.txt") %>% 
  mutate(Compartment = sample_type, host_common_name = "Rice", study = "Rice_knight") %>% 
  dplyr::select(host_common_name, sample_type, SampleID, longitude, latitude, study)

boechera_map <- read_tsv("~/Google Drive/RMB/Analyses/Combo/boechera_map.txt") %>%
  dplyr::select(SampleID, Type, Plant_ID, Site, Age) %>%
  rename(sample_type = Type) %>%
  mutate(study = "boechera_wagner", host_common_name = "rockcress") %>% 
  filter(sample_type != "leaf")

domestication_map <- read_tsv("~/Google Drive/RMB/Analyses/WEEDS/Manuscript/Data/NativePlants/TRY2/soil_domestication.map") %>% 
  rename(host_common_name = CommonName) %>% 
  mutate(study = "domestication")

vigor1_map <- read_tsv("~/RMB/SoilDomestication/Data/vigor.map") %>% 
  mutate(host_common_name = "Rice") %>% 
  mutate(study = "Seedling Vigor 1")

vigor2_map <- read_tsv("~/RMB/SoilDomestication/Data/vigor_2.map") %>% 
  mutate(host_common_name = "Rice") %>% 
  rename(Compartment = Cmpt) %>% 
  mutate(SampleID = gsub(".*:", "", SampleID)) %>% 
  mutate(study = "Seedling Vigor 2")

sedge_map <- read_tsv("~/RMB/SEDGE/sedge.map") %>% 
  rename(host_common_name = Species) %>% 
  mutate(study = "Sedge")

total_map <- as_tibble(bind_rows(maize_map, grape_map, cannabis_map, rice_map, boechera_map, domestication_map, rice_knight, vigor2_map, vigor1_map, sedge_map))
total_map %>% ungroup() %>% write_tsv("~/RMB/SoilDomestication/Data/total_map.tsv")
```

```{r}
d_data <- otu_table %>% 
  gather(SampleID, value, -OTUID) %>% rename(variable = OTUID) %>% 
  mutate(variable = factor(as.character(variable))) %>% 
  inner_join(total_map, by = "SampleID") %>% 
  inner_join(tax, by = "variable") %>% 
  filter(Family != "mitochondria" & Class != "Chloroplast") %>% 
  group_by(SampleID) %>% 
  mutate(depth = sum(value)) %>% 
  group_by(variable, study) %>% 
  mutate(RA = value / depth, prevalence = sum(value > 0) / n())
```

```{r}
d_data %>% 
  ungroup() %>% 
  dplyr::select(study, host_common_name, SampleID, depth) %>% 
  distinct() %>% 
  mutate(colorz = paste(host_common_name, study)) %>% 
  ggplot(., aes(x = depth, fill = colorz)) +
  geom_histogram() +
  scale_x_log10() +
  facet_wrap(~colorz)
```

```{r}
d_data %>% 
  filter(depth > 1000) %>% 
  mutate(discard = ifelse(prevalence >= 0.01, "Keep", "Discard")) %>% 
  group_by(variable, prevalence, discard) %>% 
  summarise(mean_ab = mean(RA)) %>% 
  ggplot(aes(x = mean_ab, y = prevalence, color = discard)) +
  geom_point(alpha = 0.2) +
  scale_color_manual(values = c("red", "black")) +
  scale_x_log10() +
  theme_minimal()
```
```{r}
d_data %>% 
  filter(depth > 1000) %>% 
  mutate(discard = ifelse(prevalence >= 0.01, "Keep", "Discard")) %>% 
  ungroup() %>% 
  dplyr::select(variable, discard) %>% 
  distinct() %>% 
  group_by(discard) %>% 
  summarise(n = n())
```

```{r}
wExp <- d_data %>% 
  filter(depth > 1000 & prevalence > 0.1) %>% 
  mutate(Compartment2 = ifelse(is.na(Compartment), sample_type, Compartment)) %>% 
  mutate(Compartment  = Compartment2) %>% 
  select(-Kingdom, -Class, -Order, -Phylum, -Phylum2, -Family, -Genus, -Species, -Cultivar, -Compartment2, -sample_type, -Plant_ID, -collection_timestamp, -longitude, -latitude, -Age)
wExp %>% 
  ungroup() %>% 
  write_rds("~/RMB/SoilDomestication/Data/wExp.rds", compress = "gz")
```



