---
title: "Native Plants Analysis"
output: html_notebook
---

```{r}
library(vegan)
library(broom)
library(MASS)
library(tidyverse)
library(broom)
library(biobroom)
library(tidyMB)
```

```{r}
## Do Not Run
#wExp <- readRDS("~/RMB/SoilDomestication/Data/wExp.rds")
#wExp %>% 
#  filter(Site == "Arkansas") %>% 
#  ungroup() %>% 
#  saveRDS("~/RMB/SoilDomestication/Data/native_plants_data.rds")

nExp <- readRDS("~/RMB/SoilDomestication/Data/native_plants_data.rds") %>% filter(SampleID != "Arw.22") %>% 
  mutate(cpm = round(value * (1000000 / depth)))
tax <- readRDS("~/RMB/SoilDomestication/Data/gg_otus_tax.rds")
```

```{r}
raref <- function(x, sampling_depth, value = "value", otus = "variable") {
  rare_values <- data.frame(table(sample(x$`variable`, sampling_depth, replace = T, prob = x$`value`/x$depth)))
  names(rare_values) <- c(otus, "rare_value")
  return(suppressMessages(left_join(x, rare_values, by = otus) %>% replace_na(list(rare_value = 0))))
}
```


```{r} 
nPC <- tidy_pcoa(nExp %>% group_by(variable) %>% filter(sum(value) > 0) %>% mutate(RA = RA*1000), dist = "bray", value = "RA", keep_loadings = T)

nPC$axes %>% 
  ggplot(aes(MDS1, MDS2, color = host_common_name)) +
  geom_point(size = 3, alpha = 0.7) +
  stat_ellipse(aes(group = Compartment), color = "black") +
  scale_color_brewer(palette = "Set1", direction = -1) +
  theme_minimal() +
  labs(x = paste("PCo1 (", round(nPC$eigen_vals[1] * 100, 2), "%)", sep = ""), y = paste("PCo2 (", round(nPC$eigen_vals[2] * 100, 2), "%)", sep = ""))
```
```{r}
long_adonis(nExp %>% mutate(RA2 = log2((RA*1000) + 1)), value = "RA2", formula = "Compartment * host_common_name")
nExp %>% 
  mutate(RA2 = log2((RA*1000) + 1)) %>% 
  group_by(Compartment) %>% 
  nest() %>% 
  filter(Compartment != "Bulk Soil") %>% 
  mutate(ad = map(data, ~long_adonis(., value = "RA2", formula = "host_common_name"))) %>% 
  unnest(map(ad, ~tidy(.)))
```


## Phyla Stuff
```{r}
phyla_abund <- nExp %>% 
  inner_join(tax, by = "variable") %>% 
  group_by(SampleID, Compartment, host_common_name, Phylum2, depth) %>% 
  summarise(phy_total = sum(value)) %>% 
  mutate(prop = (phy_total + 1) / (depth + 1)) %>% 
  group_by(Compartment) %>% 
  mutate(alpha = fitdistr(prop, dbeta, start = list(shape1 = 1, shape2 = 10))$estimate[1],
         beta = fitdistr(prop, dbeta, start = list(shape1 = 1, shape2 = 10))$estimate[2]) %>% 
  mutate(emp_estimate = (phy_total + alpha + 1) / (depth + 1 + alpha + beta))

phy_host_lm <- phyla_abund %>% 
  group_by(Compartment, Phylum2) %>% 
  filter(host_common_name != "Soil") %>% 
  mutate(host_common_name = fct_relevel(host_common_name, "Rice", "Redstem", "Sedge", "Mudplantain")) %>% 
  nest() %>% 
  mutate(models = map(data, ~tidy(lm(log2(emp_estimate) ~ host_common_name, .)))) %>% 
  unnest(models) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = gsub("host_common_name", "", term)) %>% 
  group_by(Compartment) %>% 
  mutate(p.adj = p.adjust(p.value, "fdr"))

phy_host_lm1 <- phyla_abund %>% 
  group_by(Compartment, Phylum2) %>% 
  filter(host_common_name != "Soil") %>% 
  mutate(host_common_name = fct_relevel(host_common_name, "Rice", "Redstem", "Sedge", "Mudplantain")) %>% 
  nest() %>% 
  mutate(models = map(data, ~tidy(lm(log2(phy_total + 1) ~ host_common_name, .)))) %>% 
  unnest(models) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = gsub("host_common_name", "", term)) %>% 
  group_by(Compartment) %>% 
  mutate(p.adj = p.adjust(p.value, "fdr"))

phy_comp_lm <- phyla_abund %>% 
  group_by(Phylum2) %>% 
  nest() %>% 
  mutate(models = map(data, ~tidy(lm(log2(emp_estimate) ~ Compartment, .)))) %>% 
  unnest(models) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = gsub("Compartment", "", term)) %>% 
  mutate(p.adj = p.adjust(p.value, "bon"))

phy_comp_lm %>% 
  filter(p.adj <= 0.05) %>% 
  mutate(Phylum2 = fct_reorder(factor(Phylum2), estimate)) %>% 
  ggplot(aes(Phylum2, estimate)) +
  geom_point() +
  facet_grid(. ~ term)

phy_comp_lm %>% 
  inner_join(phyla_abund %>% group_by(Phylum2, Compartment) %>% summarise(mean_ab = mean(emp_estimate)), by = c(c("term" = "Compartment"), "Phylum2")) %>% 
  mutate(Compartment = fct_relevel(term, "Rhizosphere", "Endosphere")) %>%
  ggplot(aes(Compartment, estimate, group = Phylum2, color = ifelse(p.adj <= 0.05, Compartment, "ns"), shape = ifelse(p.adj <= 0.05, "sig", "ns"), size = log2(mean_ab * 1000))) +
  geom_line(color = 'black', alpha = 0.5, size = 0.5) +
  geom_point(alpha = 0.5) +
  scale_shape_manual(values = c(1, 16)) +
  scale_color_manual(values = c("darkmagenta", "steelblue", "black")) +
  scale_size_continuous(range = c(0,10)) +
  theme_minimal()

phy_host_lm %>% 
  filter(p.adj <= 0.05) %>% ungroup() %>% 
  mutate(Compartment = fct_relevel(Compartment, "Rhizosphere", "Endosphere")) %>% 
  ggplot(aes(Phylum2, term, fill = estimate)) +
  geom_tile() +
  facet_grid(Compartment~.) +
  scale_fill_gradient2(low = "gold", high = "dodgerblue", mid = 'black') +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))
  
phyla_abund %>% 
  group_by(Phylum2) %>% 
  nest() %>% 
  mutate(total = map_dbl(data, ~sum(.x$prop))) %>% 
  top_n(15, total) %>% 
  unnest(data) %>% 
  mutate(Compartment = fct_relevel(Compartment, "Bulk Soil", "Rhizosphere", "Endosphere")) %>% 
  group_by(Compartment, host_common_name, SampleID) %>% 
  nest() %>% 
  group_by(Compartment) %>% 
  arrange(host_common_name) %>% 
  mutate(order = 1:n()) %>% 
  unnest() %>% 
  ggplot(aes(order, prop * 100, fill = Phylum2)) +
  geom_bar(stat = "identity") +
  geom_point(aes(x = order, y = -2, color = host_common_name)) +
  facet_grid(.~Compartment, scales = "free_x") +
  scale_fill_manual(values = c(brewer.pal(11, "RdGy"),brewer.pal(5, "Blues")[-1])) +
  scale_color_brewer(palette = "Set1", direction = -1) +
  labs(x = "", y = "Percent of Reads") +
  theme_minimal() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), legend.position = "bottom")
```


## Differential Abundance
```{r}
safe_glm <- possibly(glm, NA_real_)
safe_glm.nb <- possibly(glm.nb, NA_real_)

nExp2 <- nExp %>% 
  ungroup() %>% 
  mutate(variable = factor(variable)) %>% 
  group_by(SampleID) %>% 
  nest() %>% 
  mutate(rare = map(data, ~raref(., sampling_depth = 14000, value = "value"))) %>% 
  unnest(rare)

pois_glm_plant <- nExp2 %>% 
  filter(Compartment != "Bulk Soil") %>% 
  group_by(variable) %>% 
  filter(sum(rare_value > 0) / n() > 0.1) %>% 
  mutate(host_common_name = relevel(factor(host_common_name), ref = "Rice")) %>% 
  group_by(variable, Compartment) %>% 
  nest() %>%
  mutate(models = map(data, ~suppressWarnings(safe_glm(rare_value ~ host_common_name + offset(log2(depth)), family = poisson, .))))

nb_glm_plant <- nExp2 %>% 
  filter(Compartment != "Bulk Soil") %>% 
  group_by(variable) %>% 
  filter(sum(rare_value > 0) / n() > 0.1) %>% 
  mutate(host_common_name = relevel(factor(host_common_name), ref = "Rice")) %>% 
  group_by(variable, Compartment) %>% 
  nest() %>%
  mutate(models = map(data, ~suppressWarnings(safe_glm.nb(rare_value ~ host_common_name + offset(log2(depth)), .))))

nb_glm_plant_int <- nExp2 %>% 
  filter(Compartment != "Bulk Soil") %>% 
  group_by(variable) %>% 
  filter(sum(rare_value > 0) / n() > 0.1) %>% 
  mutate(host_common_name = relevel(factor(host_common_name), ref = "Rice")) %>% 
  group_by(variable) %>% 
  nest() %>%
  mutate(models = map(data, ~suppressWarnings(safe_glm.nb(rare_value ~ Compartment * host_common_name + offset(log2(depth)), .))))

lm_plant <- nExp %>% 
  filter(Compartment != "Bulk Soil") %>% 
  group_by(variable, Compartment) %>% 
  filter(sum(value > 0) / n() > 0.1) %>% 
  mutate(host_common_name = relevel(factor(host_common_name), ref = "Rice")) %>% 
  group_by(variable, Compartment) %>% 
  nest() %>%
  mutate(models = map(data, ~lm(log2((RA * 1000) + 1) ~ host_common_name, .)))

edgeR_plant <- nExp %>% 
  filter(Compartment != "Bulk Soil") %>% 
  group_by(variable) %>% 
  filter(sum(value > 0) / n() > 0.1) %>% 
  mutate(group = paste(Compartment, host_common_name, sep = ".")) %>% 
  group_by(group_var = "edgeR") %>% 
  nest() %>% 
  mutate(DGEL = map(data, ~tidyDGEL(., value = "value", group_column = "group"))) %>% 
  mutate(design = map(data, ~model.matrix(~0 + group, tidyMB::grab_metadata(.)))) %>% 
  mutate(DGEL = map(DGEL, ~edgeR::calcNormFactors(.))) %>% 
  mutate(DGEL = map2(DGEL, design, edgeR::estimateDisp)) %>% 
  mutate(fit = map2(DGEL, design, edgeR::glmFit))

my.contrasts = limma::makeContrasts(Mudplantain_RS = groupRhizosphere.Rice-groupRhizosphere.Mudplantain, 
                                    Sedge_RS = groupRhizosphere.Rice-groupRhizosphere.Sedge, 
                                    Redstem_RS = groupRhizosphere.Rice-groupRhizosphere.Redstem, 
                                    Mudplantain_ES = groupEndosphere.Rice-groupEndosphere.Mudplantain,
                                    Sedge_ES = groupEndosphere.Rice-groupEndosphere.Sedge,
                                    Redstem_ES = groupEndosphere.Rice-groupEndosphere.Redstem, levels=(edgeR_plant %>% pull(design))[[1]])

edgeR_results <- bind_rows(cbind(test = "Mudplantain_RS", dg_tidy(edgeR::glmLRT((edgeR_plant %>% pull(fit))[[1]], contrast = my.contrasts[,"Mudplantain_RS"]))),
                           cbind(test = "Sedge_RS", dg_tidy(edgeR::glmLRT((edgeR_plant %>% pull(fit))[[1]], contrast = my.contrasts[,"Sedge_RS"]))),
                           cbind(test = "Redstem_RS", dg_tidy(edgeR::glmLRT((edgeR_plant %>% pull(fit))[[1]], contrast = my.contrasts[,"Redstem_RS"]))),
                           cbind(test = "Mudplantain_ES", dg_tidy(edgeR::glmLRT((edgeR_plant %>% pull(fit))[[1]], contrast = my.contrasts[,"Mudplantain_ES"]))),
                           cbind(test = "Sedge_ES", dg_tidy(edgeR::glmLRT((edgeR_plant %>% pull(fit))[[1]], contrast = my.contrasts[,"Sedge_ES"]))),
                           cbind(test = "Redstem_ES", dg_tidy(edgeR::glmLRT((edgeR_plant %>% pull(fit))[[1]], contrast = my.contrasts[,"Redstem_ES"])))) %>% 
  separate(test, into = c("taxon", "Compartment"), sep = "_")


DESeq2_plant <- nExp %>% 
  filter(Compartment != "Bulk Soil") %>% 
  group_by(variable) %>% 
  filter(sum(value > 0) / n() > 0.1) %>% 
  mutate(host_common_name = relevel(factor(host_common_name), ref = "Rice")) %>% 
  mutate(group = paste(Compartment, host_common_name, sep = ".")) %>% 
  group_by(group_var = "DESeq2") %>% 
  nest() %>% 
  mutate(DGEL = map(data, ~tidyDGEL(., value = "value", group_column = "group", method = "DESeq2", formula = "~ group"))) %>% 
  mutate(dds = map(DGEL, ~DESeq(.))) %>% 
  mutate(Sedge_RS = map(dds, ~results(., contrast = c("group", "Rhizosphere.Rice", "Rhizosphere.Sedge")))) %>% 
  mutate(Mudplantain_RS = map(dds, ~results(., contrast = c("group", "Rhizosphere.Rice", "Rhizosphere.Mudplantain")))) %>% 
  mutate(RedStem_RS = map(dds, ~results(., contrast = c("group", "Rhizosphere.Rice", "Rhizosphere.Redstem")))) %>% 
  mutate(Sedge_ES = map(dds, ~results(., contrast = c("group", "Endosphere.Rice", "Endosphere.Sedge")))) %>% 
  mutate(Mudplantain_ES = map(dds, ~results(., contrast = c("group", "Endosphere.Rice", "Endosphere.Mudplantain")))) %>% 
  mutate(Redstem_ES = map(dds, ~results(., contrast = c("group", "Endosphere.Rice", "Endosphere.Redstem")))) %>% 
  select(Mudplantain_RS, Sedge_RS, RedStem_RS, Mudplantain_ES, Sedge_ES, Redstem_ES, group_var) 


```


```{r}
pois_glm %>% 
  unnest(map(models, ~tidy(.))) %>% 
  mutate(p.adj = p.adjust(p.value, "fdr")) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(direction = ifelse(estimate > 0, "Weed", "Rice")) %>% 
  mutate(term = gsub("host_common_name", "", term)) %>% 
  filter(p.adj <= 0.05) %>% 
  dplyr::count(direction, Compartment, variable) %>% 
  dplyr::add_count(direction, Compartment) %>% 
  filter(n == 3)

intersect_nb_glm <- nb_glm_plant %>% 
  unnest(map(models, ~tidy(.))) %>% 
  mutate(p.adj = p.adjust(p.value, "fdr")) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(direction = ifelse(estimate > 0, "Weed", "Rice")) %>% 
  mutate(term = gsub("host_common_name", "", term)) %>% 
  filter(p.adj <= 0.05) %>% 
  dplyr::count(direction, Compartment, variable) %>% 
  dplyr::add_count(direction, Compartment) %>% 
  filter(n == 3)

intersect_lm <- lm_plant %>% 
  unnest(map(models, ~tidy(.))) %>% 
  mutate(p.adj = p.adjust(p.value, "fdr")) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(direction = ifelse(estimate > 0, "Weed", "Rice")) %>%
  mutate(term = gsub("host_common_name", "", term)) %>% 
  filter(p.adj <= 0.05) %>% 
  dplyr::count(direction, Compartment, variable) %>% 
  dplyr::add_count(direction, Compartment) %>% 
  filter(n == 3)

intersect_deseq <- DESeq2_plant %>% 
  select(Mudplantain_RS, Sedge_RS, RedStem_RS, Mudplantain_ES, Sedge_ES, RedStem_ES, group_var) %>% 
  gather(key = taxon, value = results, -group_var) %>% 
  unnest(map(results, ~tidy(.))) %>% 
  separate(taxon, sep = "_", into = c("Taxon", "Compartment")) %>% 
  mutate(direction = ifelse(estimate < 0, "Weed", "Rice")) %>% 
  filter(p.adjusted <= 0.05) %>% 
  dplyr::count(direction, Compartment, gene) %>% 
  dplyr::add_count(direction, Compartment) %>% 
  filter(n == 3) %>% 
  mutate(Compartment = gsub("ES", "Endosphere", Compartment),
         Compartment = gsub("RS", "Rhizosphere", Compartment)) %>% 
  dplyr::rename(variable = gene)

intersect_edger <- edgeR_results %>% 
  group_by(Compartment, taxon) %>% 
  mutate(p.adj = p.adjust(p.value, "fdr")) %>% 
  filter(p.adj <= 0.01) %>% 
  mutate(direction = ifelse(logFC < 0, "Weed", "Rice")) %>% ungroup() %>% 
  dplyr::count(direction, Compartment, variable) %>% 
  dplyr::add_count(direction, Compartment) %>% 
  filter(n == 3) %>% 
  mutate(Compartment = gsub("ES", "Endosphere", Compartment),
         Compartment = gsub("RS", "Rhizosphere", Compartment))

intersect_edger %>% 
  dplyr::count(direction, Compartment, nn)

intersect_edger %>% inner_join(intersect_lm, by = c("variable", "Compartment", "direction")) %>% dplyr::count(Compartment, direction)
intersect_lm %>% dplyr::count(Compartment, direction, nn)
intersect_edger %>% dplyr::count(Compartment, direction, nn) %>% mutate(prop = nnn/nn)

intersects <- intersect(intersect_lm %>% filter(Compartment == "Endosphere" & direction == "Rice") %>% pull(variable),
                 intersect_edger %>% filter(Compartment == "Endosphere" & direction == "Rice") %>% pull(variable))
diff <- setdiff(intersect_edger %>% filter(Compartment == "Endosphere" & direction == "Weed") %>% pull(variable),
        intersect_lm %>% filter(Compartment == "Endosphere" & direction == "Weed") %>% pull(variable))
        
dg_tidy <- function(x){
  newt <- x$table
  newt$gene <- row.names(newt)
  return(as_tibble(newt) %>% 
           dplyr::rename(variable = gene) %>% 
           dplyr::rename(p.value = PValue))
}

```

```{r}
edgeR_results %>%
  mutate(p.adj = p.adjust(p.value, "fdr")) %>% 
  filter(p.adj <=0.05) %>% 
  ggplot(aes(logFC)) +
  geom_histogram() +
  facet_grid(Compartment ~ taxon)

edgeR_results %>%
  mutate(p.adj = p.adjust(p.value, "fdr")) %>% 
  filter(p.adj <=0.05) %>% 
  ggplot(aes(logFC)) +
  geom_histogram() +
  facet_grid(Compartment ~ taxon)

lm_plant %>%
  unnest(map(models, ~tidy(.))) %>% 
  mutate(p.adj = p.adjust(p.value, "fdr")) %>% 
  filter(p.adj <= 0.05) %>% 
  filter(term != "(Intercept)") %>% 
  arrange(abs(estimate))
  
  ggplot(aes(estimate)) +
  geom_histogram() +
  facet_grid(Compartment ~ term)
```


```{r}
lm_plant %>% 
  unnest(map(models, ~tidy(.))) %>% 
  mutate(p.adj = p.adjust(p.value, "fdr")) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(direction = ifelse(estimate > 0, "Weed", "Rice")) %>%
  mutate(term = gsub("host_common_name", "", term)) %>% 
  filter(p.adj <= 0.05) %>% 
  dplyr::count(Compartment, direction, term) %>% 
  arrange(direction) %>% 
  arrange(Compartment)

DESeq2_plant %>% 
  select(Mudplantain_RS, Sedge_RS, RedStem_RS, Mudplantain_ES, Sedge_ES, Redstem_ES, group_var) %>% 
  gather(key = taxon, value = results, -group_var) %>% 
  unnest(map(results, ~tidy(.))) %>% 
  separate(taxon, sep = "_", into = c("Taxon", "Compartment")) %>% 
  mutate(direction = ifelse(estimate < 0, "Weed", "Rice")) %>% 
  filter(p.adjusted <= 0.005) %>% 
  dplyr::count(Compartment, direction, Taxon) %>% 
  arrange(direction) %>% 
  arrange(Compartment)

edgeR_results %>% 
  group_by(Compartment, taxon) %>% 
  mutate(p.adj = p.adjust(p.value, "fdr")) %>% 
  filter(p.adj <= 0.009) %>% 
  mutate(direction = ifelse(logFC < 0, "Weed", "Rice")) %>% ungroup() %>% 
  dplyr::count(direction, Compartment, variable) %>%
  filter(n == 3) %>% 
  dplyr::count(direction, Compartment)
  arrange(direction) %>% 
  arrange(Compartment)
```  

```{r}
DESeq2_plant %>% 
  select(Mudplantain_RS, Sedge_RS, RedStem_RS, Mudplantain_ES, Sedge_ES, RedStem_ES, group_var) %>% 
  gather(key = taxon, value = results, -group_var) %>% 
  unnest(map(results, ~tidy(.))) %>% 
  separate(taxon, sep = "_", into = c("Taxon", "Compartment")) %>% 
 # filter(abs(estimate) <10) %>% 
  ggplot(aes(baseMean, estimate, color = ifelse(p.adjusted <= 0.05, "s", "ns"))) +
    geom_point() +
    facet_grid(Compartment ~ Taxon) +
    scale_x_log10()

nExp %>% 
  filter(variable == "995662") %>% 
  ggplot(aes(host_common_name, log2((RA * 1000) + 1), color = host_common_name)) +
  geom_jitter(height = 0, width = 0.1) +
  facet_grid(.~Compartment) +
  scale_y_log10()

j<-nExp2 %>% 
  filter(variable == "995662" & Compartment != "Bulk Soil") %>% 
  group_by(Compartment, host_common_name, SampleID) %>% 
  nest() %>% 
  group_by(Compartment, host_common_name) %>% 
  sample_n(4) %>% 
  unnest() %>% ungroup() %>% 
  mutate(host_common_name = relevel(factor(host_common_name), ref = "Rice")) %>% 
  group_by(Compartment) %>% 
  nest() %>% 
  mutate(model = map(data, ~glm.nb(rare_value ~ host_common_name + offset(log2(depth + 1)), .))) %>% 
  unnest(map(model, ~tidy(.)))

j<-nExp2 %>% 
  filter(variable == "995662" & Compartment != "Bulk Soil") %>% 
  group_by(Compartment, host_common_name, SampleID) %>% 
  nest() %>% 
  group_by(Compartment, host_common_name) %>% 
  sample_n(4) %>% 
  unnest() %>% ungroup() %>% 
  mutate(host_common_name = relevel(factor(host_common_name), ref = "Rice")) %>% 
  group_by(Compartment) %>% 
  nest() %>% 
  mutate(model = map(data, ~lm(log2((RA*1000) + 1) ~ host_common_name, .))) %>% 
  unnest(map(model, ~tidy(.)))

lm_plant %>% filter(variable == "995662") %>% 
  unnest(map(models, ~tidy(.)))

nExp %>% 
  filter(variable%in%get("intersects")) %>% 
  ggplot(aes(host_common_name, log2((RA * 1000) + 1), color = host_common_name)) +
  geom_jitter(height = 0, width = 0.1) +
  facet_grid(.~Compartment) +
  scale_y_log10()


DESeq2_plant %>%
  filter(gene == "3738841")
edgeR_results %>% 
  filter(variable == "3738841")

nExp %>% 
  filter(Compartment == "Endosphere" & variable == "105600") %>% 
  kruskal.test(log2((RA * 1000) + 1) ~ host_common_name, data = .)
```

