---
title: "Soil Domestication"
output: html_notebook
---

```{r}
library(vegan)
library(broom)
library(tidyverse)
library(broom)
library(biobroom)
library(tidyMB)
```

```{r}
## Do Not Run
#wExp <- read_rds("~/Google Drive/RMB/Analyses/WEEDS/Manuscript/wExp.rds")
#wExp %>% 
#  filter(Experiment == "Mix" | Experiment == "Transplant") %>% 
#  ungroup() %>% 
#  group_by(variable) %>% 
#  filter(sum(value) > 0) %>% 
#  saveRDS("~/RMB/SoilDomestication/Data/dom_data.rds")

dExp <- readRDS("~/RMB/SoilDomestication/Data/dom_data.rds")
tax <- readRDS("~/RMB/SoilDomestication/Data/gg_otus_tax.rds")
```


```{r}
dPC <- tidy_pcoa(dExp %>% mutate(RA = RA*1000), dist = "bray", value = "RA", keep_loadings = T)

dPC$axes %>% 
  ggplot(aes(MDS1, MDS2, color = From, shape = Experiment)) +
  geom_point(size = 3, alpha = 0.7) +
  stat_ellipse(aes(group = Compartment), color = "black") +
  scale_color_manual(values = c("dodgerblue", "gold")) +
  theme_minimal() +
  labs(x = paste("PCo1 (", round(nPC$eigen_vals[1] * 100, 2), "%)", sep = ""), y = paste("PCo2 (", round(nPC$eigen_vals[2] * 100, 2), "%)", sep = ""))
```

```{r}
dom_deseq <- dExp %>% 
  group_by(variable) %>% 
  filter(sum(value > 0) / n() > 0.1) %>% 
  mutate(group = paste(Compartment, From, sep = ".")) %>% 
  group_by(group_var = "DESeq2", Experiment) %>% 
  nest() %>% 
  mutate(DGEL = map(data, ~tidyDGEL(., value = "value", group_column = "group", method = "DESeq2", formula = "~ group"))) %>% 
  mutate(dds = map(DGEL, ~DESeq(.))) %>% 
  mutate(BulkSoil = map(dds, ~results(., contrast = c("group", "Bulk Soil.A", "Bulk Soil.N")))) %>% 
  mutate(Rhizosphere = map(dds, ~results(., contrast = c("group", "Rhizosphere.A", "Rhizosphere.N")))) %>% 
  mutate(Endosphere = map(dds, ~results(., contrast = c("group", "Endosphere.A", "Endosphere.N")))) %>% 
  select(BulkSoil, Rhizosphere, Endosphere, Experiment) %>% 
  gather(key = Compartment, value = results, -Experiment)

dom_otus <- dom_deseq %>% 
  unnest(map(results, ~tidy(.))) %>% 
  group_by(Experiment, Compartment) %>% 
  mutate(direction = ifelse(estimate > 0, "A", "N")) %>% 
  filter(p.adjusted <= 0.05) %>% ungroup() %>% 
  dplyr::count(direction, Compartment, gene) %>% 
  filter(n == 2) %>% 
  dplyr::count(direction, gene) %>% 
  filter(direction == "A") %>% 
  dplyr::rename(variable = gene)

```

### What is the overlap of rice enriched microbes with the domesticated microbes?
```{r}
(nA <- length(unique(rice_otus$variable)))
(nB <- length(unique(dom_otus$variable)))
(nC <- length(union(nExp %>% group_by(variable) %>% filter(sum(value > 0) / n() > 0.1) %>% dplyr::count(variable) %>% pull(variable),
          dExp %>% group_by(variable) %>% filter(sum(value > 0) / n() > 0.1) %>% dplyr::count(variable) %>% pull(variable))))
(nAB <- length(intersect(dom_otus$variable, rice_otus$variable)))

phyper(nAB, nA, nC-nA, nB, lower.tail = F)

```

